language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install -qq libeigen3-dev 
  - git clone https://github.com/traversaro/orocos_kinematics_dynamics
  - cd orocos_kinematics_dynamics/orocos_kdl
  - mkdir build 
  - cd build
  - cmake ../
  - make
  - sudo make install
  - cd ../../..
  - mkdir build
  - cd build
  - cmake -DCREATE_TESTS:BOOL=ON -DCMAKE_CXX_FLAGS:STRING="-Wall" ./..

script: make && make test
