language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install -qq libboost-system-dev libboost-thread-dev libtinyxml-dev
  - sudo chmod +x ./.travis/build_urdfdom
  - ./.travis/build_urdfdom
  - sudo apt-get install -qq libeigen3-dev
  - git clone https://github.com/traversaro/orocos_kinematics_dynamics
  - cd orocos_kinematics_dynamics/orocos_kdl
  - mkdir build
  - cd build
  - cmake ../
  - make
  - sudo make install
  - cd ../../..
  - git clone https://github.com/traversaro/kdl_codyco
  - cd kdl_codyco
  - git checkout experimental
  - mkdir build
  - cd build
  - cmake ../
  - make
  - sudo make install
  - cd ../..
  - mkdir build
  - cd build
  - cmake -DCREATE_TESTS:BOOL=ON -DCMAKE_BUILD_TYPE=Debug ./..

script: make && make test
